POST /api/v1/store/purchase HTTP/1.1
Content-Type: application/json
Host: localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9raXRhMyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNTg4MzYxNiwiZXhwIjoxNzE3MDkzMjE2fQ.Q69mN4crndK5jvR744sOz9jLntcLGxGlcWLBLsUZI70
Content-Length: 85

{
	"name": "milho",
	"number": 0,
	"itemId": "8221bb9b-1ec7-4051-a762-3ad97d786002" // UUIDv4 for the item
}
