import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
export const metadata: Metadata = {
  title: "Next.js2",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
