POST /api/v1/boom/schedule HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9raXRhMyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNzYzMTUzMSwiZXhwIjoxNzE4ODQxMTMxfQ.mddZnrTccGRmTw7OCpXFECJTVTkG13u6u7_LWvfF7Ts

{
  "name": "paiero",
  "partyId": "sao_login",
  "startInSeconds": 60,
  "duration": 10
}

###

GET /api/v1/boom/schedule?partyId=sao_login HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9raXRhMyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNzYzMTUzMSwiZXhwIjoxNzE4ODQxMTMxfQ.mddZnrTccGRmTw7OCpXFECJTVTkG13u6u7_LWvfF7Ts
